# Generated by Django 6.0.7 on 2026-07-15 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('admin_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LoginData',
            fields=[
                ('login_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('usertype', models.CharField(choices=[('admin', 'Admin'), ('member', 'Member')], default='member', max_length=10)),
            ],
        ),
    ]
