# Generated by Django 6.0.7 on 2026-07-18 07:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_group_members'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('expense_id', models.AutoField(primary_key=True, serialize=False)),
                ('group_id', models.CharField(max_length=20)),
                ('paid_by', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=150)),
                ('amount', models.IntegerField()),
                ('split_type', models.CharField(choices=[('equal', 'Equal'), ('custom', 'Custom')], default='equal', max_length=10)),
                ('split_data', models.TextField()),
                ('expense_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
