# Generated by Django 6.0.7 on 2026-07-22 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_expenseapproval_groupmessage_expense_payment_mode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('group_id', models.CharField(max_length=20)),
                ('payer_email', models.CharField(max_length=100)),
                ('receiver_email', models.CharField(max_length=100)),
                ('amount_paise', models.IntegerField()),
                ('note', models.CharField(blank=True, max_length=255)),
                ('mode', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], default='offline', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
